[lb]
lb01 ansible_host=10.0.0.205 internal_ip=172.16.1.205 router_id=lb01 state=MASTER priority=150 nopreempt=false
lb02 ansible_host=10.0.0.206 internal_ip=172.16.1.206 router_id=lb02 state=BACKUP priority=100 nopreempt=true

[web]
web01 ansible_host=10.0.0.207 internal_ip=172.16.1.207
web02 ansible_host=10.0.0.208 internal_ip=172.16.1.208

[nfs]
nfs01 ansible_host=10.0.0.231 internal_ip=172.16.1.231

[backup]
backup01 ansible_host=10.0.0.241 internal_ip=172.16.1.241

[db]
db01 ansible_host=10.0.0.251 internal_ip=172.16.1.251
db02 ansible_host=10.0.0.252 internal_ip=172.16.1.252

[rd]
rd01 ansible_host=10.0.0.253 internal_ip=172.16.1.253

[ruoyi_web]
web03 ansible_host=10.0.0.209 internal_ip=172.16.1.209
web04 ansible_host=10.0.0.210 internal_ip=172.16.1.210

[ruoyi_webback]
web03

[ruoyi_webfront]
web04

[managed:children]
lb
web
nfs
backup
db
rd
ruoyi_web
